module.exports = {
	//Locators
	baseUrl: 'https://www.univerzalno.com/',
	featuredItemName: '210,00 KM 230,00 KM Xiaomi Redmi 9A Sport 32GB (2GB RAM)',
    addToCart: 'Dodaj u korpu',
    backToShopping: 'Back to shopping',
    baseTitle: "Home - univerzalno.com",
    shopUrl: "Shop - univerzalno.com",
    myAccount: '| v Moj račun',
    regMailID: '#reg_email',
    regPassID: '#reg_password',
    regBtn: 'Registracija',
    accountUrl: 'Moj račun - univerzalno.com',
    PCPage: 'https://www.univerzalno.com/proizvodi/laptop-pc-i-oprema/',
    filterBtn: 'Filter',
    categoryDropDown: 'Prikaži sve kategorije',
    inchBtn: '17"',
    inchFilterPage: ' 17\" Archives - univerzalno.com',
    filterPage: "Laptopi, PC i oprema Archives - univerzalno.com",
    filterPageUrl: 'https://www.univerzalno.com/proizvodi/laptop-pc-i-oprema/?min_price=0&max_price=5150',
    brand: 'Acer',
    OS: 'Windows 11',
    homePage: 'univerzalno.com',
    logoID: '#masthead',
    fbLink: ' Facebook',
    fbURL: 'https://www.facebook.com/univerzalno',
    twitterLink: ' Twitter',
    twitterURL: 'https://twitter.com/univerzalno/',
    //linkedInLink: ' LinkedIn' ,
    linkedInTitle: 'Sign In | LinkedIn',
    //igLink: ' Instagram',
    //igURL: 'https://www.instagram.com/univerzalno_com/',
    loginBtn: 'Prijava',
}