module.exports = {
	//Locators
	baseUrl: 'https://www.univerzalno.com/',
	featuredItemName: '210,00 KM 230,00 KM Xiaomi Redmi 9A Sport 32GB (2GB RAM)',
    addToCart: 'Dodaj u korpu',
    backToShopping: 'Back to shopping',
    baseTitle: "Home - univerzalno.com",
    shopUrl: "Shop - univerzalno.com",
    myAccount: '| v Moj račun',
    regMailID: '#reg_email',
    regPassID: '#reg_password',
    regBtn: 'Registracija',
    accountTitle: 'Moj račun - univerzalno.com',
    PCPage: 'https://www.univerzalno.com/proizvodi/laptop-pc-i-oprema/',
    filterBtn: 'Filter',
    categoryDropDown: 'Prikaži sve kategorije',
    inchBtn: '17"',
    inchFilterPage: ' 17\" Archives - univerzalno.com',
    filterPage: "Laptopi, PC i oprema Archives - univerzalno.com",
    filterPageUrl: 'https://www.univerzalno.com/proizvodi/laptop-pc-i-oprema/?min_price=0&max_price=5150',
    brand: 'Acer',
    OS: 'Windows 11',
    homePage: 'univerzalno.com',
    logoID: '#masthead',
    fbLink: ' Facebook',
    fbURL: 'https://www.facebook.com/univerzalno',
    twitterLink: ' Twitter',
    twitterURL: 'https://twitter.com/univerzalno/',
    //linkedInLink: ' LinkedIn' ,
    linkedInTitle: 'Sign In | LinkedIn',
    //igLink: ' Instagram',
    //igURL: 'https://www.instagram.com/univerzalno_com/',
    loginBtn: 'Prijava',



    baseLink: 'link',
    baseName: '| v Moj račun',
    loginFunc: 'Prijava Prijavi se na svoj univerzalno.com račun i pregledaj dosadašnje kupovine',
    userName_email:'Korisničko ime ili email adresa *',
    userEmailDummy: 'kenansabipsn@gmail.com',
    passwordHolder: '#password',
    passwordDummy: 'YYMk7GL8jcjmkn4',
    buttonFunc: 'button',
    login: 'prijava',
    helloText: 'Pozdrav kenansabipsn',
    accountUrl:'https://www.univerzalno.com/moj-racun/',
    registrationFunc: 'Registracija Kreirajte svoj univerzalno.com račun i iskoristite prednosti kupovine za naše kupce.',
    registrationMailDummy: 'dummy3@gmail.com',
    userName_regEmail: '#reg_email',
    regPasswordHolder: '#reg_password',
    regPasswordDummy: 'Q-LAj3HjcCdv:-R',
    registration: 'Registracija',
    regHelloText: 'Pozdrav dummy3',
    accountUrl1: 'https://www.univerzalno.com/moj-racun/odjava/?_wpnonce=6b9fca230a',
    logOutText: 'Pozdrav kenansabipsn (nisi kenansabipsn? Odjava)',
    logOut: 'Odjava',
    searchBar: 'Search for:',
    searchTerm: 'Samsung A04 64GB',
    searchTitle: 'You searched for Samsung A04 64GB - univerzalno.com',
    productName:'320,00 KM 350,00 KM Samsung Galaxy A04 64GB (4GB RAM)',
    productTitle:'Samsung Galaxy A04 64GB (4GB RAM) - univerzalno.com',
    shopTitle:'Shop - univerzalno.com',
    invalidLoginEmail: 'Ismaraganovic69@gmail.com',
    invalidLoginPassword: 'caminaminaee',
    invalidRegEmail: 'ramsi', 
    invalidRegPass: 'caminaminaee',


    contactName: '| Kontakt',
    appleServ: '#topbar-right-menu-item-114607',
    appleName: 'Apple Servis',
    servisName: '| Servis',
    mLocation: '#masthead',
    mainLink: 'univerzalno.com',
    mapLocator: '.kc-google-maps',
    mapLocator2: '#post-123519 iframe',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    oNama: 'O nama',
    ilidza: 'ILIDŽA',
    popup: 'popup',
    viewMap: 'View larger map',
    dialogue: '[data-testid="dialog_iframe"]',
    startChat: 'Start chat',
    guestCont: 'Continue as guest',
    hours: 'What are your business hours?',
    closeFunc: 'close',
    addItem: 'Dodaj “TCL televizor 43P615” u Vašu korpu.',
    clickItem: 'a 1 Vaša korpa 859,00 KM ',
    cart: '#site-header-cart',
    vivax: 'TCL televizor 43P615',
    seeCart: 'Vidi korpu',
    search: 'Search for:',
    samsung: 'Samsung',
    formFunc: 'form',
    filterName: 'Search for: 10 results are available, use up and down arrow keys to navigate.Sam',
    productCat: '#product_cat',
    phones: 'mobiteli',
    question: '',
    tablist: 'tablist',
    b: 'B',
    divMain: '#main div',
    filterText: 'FiltersRezultati pretrage: “Samsung” Prikaži 16Prikaži 32Prikaži 64Prikaži All R',
    filterLoc: 'select[name="ppp"]',
    sixteen: '16',
    samsungLink: 'https://www.univerzalno.com/?s=Samsung&product_cat=mobiteli&post_type=product',
    combobox: 'combobox',
    order: 'Narudžba',
}